export const easyWords = [
    "cat", "dog", "sun", "run", "jump", "blue", "red", "fast", "slow", "big",
    "small", "tree", "bird", "fish", "book", "pen", "desk", "lamp", "hat", "cap",
    "sky", "star", "moon", "fire", "ice", "hot", "cold", "wet", "dry", "soft",
    "hard", "long", "easy", "kind", "play", "sing", "walk", "talk", "look", "see",
    "hand", "foot", "head", "face", "eye", "ear", "nose", "mouth", "arm", "leg",
    "door", "wall", "floor", "roof", "gate", "road", "park", "lake", "hill", "wind",
    "rain", "snow", "milk", "cake", "pear", "apple", "grape", "box", "bag", "cup",
    "fork", "spoon", "plate", "bowl", "chair", "bed", "ball", "bat", "ship", "boat",
    "car", "bus", "bike", "plane", "train", "gold", "silver", "iron", "rock", "sand",
    "dirt", "leaf", "root", "seed", "rose", "lily", "bell", "drum", "flag", "star",
    "milkman", "candy", "pillow", "blanket", "button", "window", "mirror", "clock", "cookie", "shadow",
    "ribbon", "puzzle", "garden", "butter", "cheese", "breeze", "candle", "needle", "thread",
    "pocket", "ticket", "magnet", "bagel", "camera", "basket", "helmet", "wallet", "socks", "jacket",
    "sweater", "tomato", "onion", "banana", "orange", "pepper", "lettuce", "castle", "bridge",
    "island", "harbor", "cottage", "bucket", "ladder", "racket", "pencil", "eraser", "notebook", "staple",
    "magpie", "saddle", "ferry", "lantern", "bottle", "whistle",
    "arrow", "badge", "blast", "blaze", "blink", "block", "bloom", "bound", "brace", "brave",
    "bright", "brisk", "brook", "brush", "buddy", "bunny", "cabin", "cargo", "catch", "cedar",
    "chalk", "charm", "chase", "chest", "chime", "chimp", "chunk", "clamp", "clash", "clasp",
    "clean", "clear", "click", "cliff", "climb", "cling", "close", "cloud", "clown", "coach",
    "cobra", "comic", "coral", "couch", "count", "court", "craft", "crane", "crash", "crazy",
    "creek", "crisp", "cross", "crowd", "crown", "crush", "crust", "curry", "cycle", "daisy",
    "dance", "dares", "darts", "dates", "dawn", "denim", "depot", "derby", "disco", "ditch",
    "ditty", "diver", "dizzy", "dodge", "doing", "domed", "donut", "dowel", "draft", "drain",
    "drape", "drawl", "dream", "dress", "dried", "drift", "drink", "drive", "drown", "ducks",
    "dunce", "eagle", "earth", "eight", "elbow", "elder", "elves", "ember", "emoji", "empty",
    "entry", "equal", "essay", "event", "exact", "extra", "fable", "faint", "faith", "falls",
    "fancy", "fangs", "feast", "fence", "fetch", "field", "fiery", "fifth", "fifty", "fight",
    "final", "finds", "first", "fixed", "flame", "flare", "flash", "flask", "flair", "fleck",
    "fleet", "flier", "fling", "flint", "flips", "float", "flood", "floor", "floss", "flour",
    "fluff", "flute", "focal", "foggy", "folly", "force", "forge", "forth", "forum", "found",
    "frame", "fresh", "friar", "frill", "frisk", "front", "frost", "froze", "fruit", "fully",
    "funds", "funny", "furry", "fused", "fuzzy", "gavel", "gecko", "genre", "ghost", "girth",
    "given", "glade", "gland", "glare", "glass", "glaze", "gleam", "glide", "gloss", "glove",
    "glyph", "gnome", "going", "grace", "grade", "graft", "grain", "grand", "grant", "graph",
    "grasp", "grass", "graze", "great", "greed", "green", "greet", "grief", "grind", "groan",
    "groin", "grope", "group", "grove", "growl", "gruel", "grump", "guard", "guava", "guess",
    "guile", "guise", "gulch", "gulls", "gummy", "gusts", "gypsy", "habit", "halve", "happy",
    "haste", "haven", "hazel", "heart", "heavy", "hedge", "heist", "herby", "heron", "herbs",
    "hinge", "hippo", "hoard", "hobby", "holly", "honey", "honor", "hooks", "hoppy", "horse",
    "hotel", "hover", "howdy", "hunch", "husky", "hyena", "igloo", "image", "infer", "inlet",
    "inner", "input", "inter", "intro", "ivory", "japan", "joust", "juicy", "jumbo", "kiwi",
    "kneel", "knife", "knock", "known", "koala", "kudos", "lance", "lapse", "latch", "later",
    "latte", "laugh", "layer", "leach", "leapt", "ledge", "leech", "lever", "light", "lilac",
    "limbo", "liner", "llama", "lodge", "lofty", "logic", "login", "lords", "lover", "lower",
    "lucky", "lumen", "lunar", "lunch", "lusty", "lychee", "lyric", "magic", "major", "maker",
    "mango", "manor", "maple", "march", "marks", "marsh", "match", "maybe", "mayor", "melon",
    "mercy", "merge", "merry", "metal", "meter", "might", "miles", "mince", "miner", "mirth",
    "mixed", "mocha", "model", "mogul", "moose", "moral", "mossy", "motor", "mount", "mouse",
    "muddy", "muffs", "mural", "murky", "music", "musty", "nacho", "naive", "nanny", "naval",
    "nifty", "night", "ninja", "nippy", "nitro", "noble", "north", "novel", "nudge", "nurse",
    "nutty", "nymph", "ocean", "offer", "olive", "onward", "optic", "orbit", "order", "otter",
    "ought", "outer", "outdo", "ozone", "pacify", "pagoda", "paint", "pansy", "pasta", "patch",
    "pause", "peach", "pearl", "pedal", "penny", "perch", "pesky", "phone", "photo", "piano",
    "piggy", "pilot", "pinch", "pipette", "pixel", "pizza", "place", "plaid", "plain", "plank",
    "plant", "plaza", "plead", "plumb", "plume", "plunk", "point", "poise", "poker", "polar",
    "polka", "porch", "porky", "pouch", "power", "press", "price", "pride", "prime", "prism",
    "probe", "prone", "prong", "proud", "proxy", "psalm", "pudgy", "pulse", "punch", "puppy",
    "pygmy", "quack", "queen", "quest", "queue", "quick", "quiet", "quill", "quota", "rabbi",
    "radar", "radio", "rainy", "rally", "ramen", "ranch", "range", "rapid", "raven", "razor",
    "reach", "realm", "rebel", "recap", "relic", "remix", "rider", "ridge", "right", "risky",
    "rival", "river", "robot", "rocky", "rodeo", "rogue", "roman", "roomy", "rouge", "rough",
    "round", "rugby", "ruler", "rumor", "rusty", "safari", "salad", "salsa", "salty", "sauce",
    "scale", "scamp", "scarf", "scene", "scent", "scone", "scope", "score", "scout", "screw",
    "scrub", "serum", "seven", "shade", "shaft", "shake", "shale", "shall", "shame", "shark",
    "sharp", "shawl", "sheep", "shelf", "shell", "shift", "shore", "short", "shout", "shove",
    "shown", "shrug", "sight", "silky", "since", "sixth", "sixty", "skate", "skier", "skill",
    "skimp", "skull", "skunk", "slant", "slate", "slave", "sleek", "sleep", "sleet", "slick",
    "slide", "sling", "slink", "slope", "sloth", "slump", "slunk", "slurp", "smack", "small",
    "smart", "smash", "smear", "smell", "smelt", "smile", "smirk", "smite", "smoke", "snack",
    "snail", "snake", "snare", "sneak", "sneer", "sniff", "snoop", "snore", "snort", "snout",
    "snowy", "snuck", "soggy", "solar", "solid", "solve", "sonic", "sorrel", "sorry", "south",
    "space", "spark", "spear", "speck", "speed", "spell", "spend", "spice", "spill", "spine",
    "spire", "spoil", "spoke", "spook", "spoon", "spore", "sport", "spout", "spray", "spree",
    "sprig", "spunk", "squad", "squat", "squid", "stage", "stain", "stale", "stall", "stamp",
    "stand", "stark", "stash", "state", "steam", "steel", "steep", "steer", "stern", "stiff",
    "still", "sting", "stock", "stomp", "stone", "stony", "store", "stork", "storm", "story",
    "stove", "strap", "stray", "strip", "strut", "study", "stump", "stung", "stunt", "style",
    "sugar", "suite", "sulky", "sunny", "super", "surge", "swamp", "swarm", "swear", "sweet",
    "swept", "swill", "swipe", "swirl", "swoop", "sword", "syrup", "table", "tabby", "talon",
    "tango", "tangy", "tapir", "taunt", "tawny", "teach", "tease", "teddy", "tempo", "tense",
    "tenth", "their", "theme", "thick", "thing", "thorn", "those", "three", "threw", "throw",
    "thumb", "thump", "tiger", "tight", "tired", "titan", "toast", "today", "token", "tools",
    "topaz", "torso", "total", "touch", "towel", "tower", "toxic", "trace", "track", "tract",
    "trade", "trail", "tramp", "trash", "trawl", "tread", "treat", "trend", "trial", "trick",
    "troop", "trout", "trove", "truce", "truck", "truly", "trump", "trunk", "trust", "truth",
    "tulip", "tummy", "tuner", "tunic", "twirl", "twist", "typed", "udder", "ulcer", "ultra",
    "uncle", "under", "union", "until", "urban", "usher", "usual", "utter", "vague", "valid",
    "valor", "value", "valve", "vapid", "vault", "venom", "verse", "vicar", "video", "vigor",
    "viola", "viper", "viral", "visit", "vista", "vivid", "vocal", "vodka", "voice", "voter",
    "vouch", "vulva", "wafer", "waltz", "waste", "watch", "water", "weary", "wedge", "weigh",
    "weird", "whack", "whale", "wheat", "wheel", "where", "which", "while", "whine", "white",
    "whole", "whose", "widen", "witty", "woman", "world", "wring", "wrist", "wrong", "yacht",
    "yearn", "yodel", "young", "yours", "youth", "zappy", "zebra", "zesty", "zippy"
];

export const normalWords = [
    "algorithm", "function", "variable", "constant", "iteration",
    "syntax", "compiler", "debugging", "interface", "protocol",
    "asynchronous", "callback", "promise", "database", "encryption",
    "frontend", "backend", "middleware", "framework", "library",
    "deployment", "repository", "abstraction", "polymorphism", "inheritance",
    "encapsulation", "architecture", "microservice", "container", "virtualization",
    "responsive", "performance", "optimization", "scalability", "accessibility",
    "development", "production", "staging", "environment", "dependency",
    "concurrency", "parallelism", "serialization", "deserialization", "hexadecimal",
    "binary", "boolean", "integer", "string", "character",
    "lightning", "mountain", "keyboard", "strength", "horizon",
    "symphony", "paradox", "velocity", "quantum", "gravity",
    "perspective", "creative", "efficient", "powerful", "dynamic",
    "validation", "authentication", "authorization", "infrastructure", "initialization",
    "documentation", "specification", "implementation", "visualization", "manipulation",
    "configuration", "notification", "registration", "transformation", "translation",
    "computation", "communication", "integration", "navigation", "publication",
    "celebration", "competition", "imagination", "inspiration", "motivation",
    "preparation", "presentation", "recognition", "reflection", "satisfaction",
    "traditional", "fundamental", "substantial", "artificial", "intelligence",
    "blockchain", "cryptography", "distributed", "decentralized", "observation",
    "synthesis", "modular", "throughput", "latency", "bandwidth",
    "orchestration", "provisioning", "benchmark", "refactor", "idempotent",
    "heuristic", "annotation", "immutable", "convention",
    "prototype", "monolithic", "observability", "telemetry",
    "profiling", "containerize", "rollback", "endpoint", "payload",
    "handshake", "compression", "throttling",
    "caching", "replication", "sharding", "partition", "indexing", "normalization",
    "denormalize", "scheduler", "mutex", "semaphore", "checkpoint",
    "transcoding", "safeguard",
    "abundance", "accuracy", "advantage", "ambition", "awareness",
    "balance", "boldness", "brevity", "brilliance", "capability",
    "challenge", "clarity", "coalition", "coherence", "commitment",
    "complexity", "concept", "conflict", "connection", "consensus",
    "context", "contrast", "courage", "credibility", "culture",
    "curiosity", "decision", "delivery", "democracy", "discovery",
    "diversity", "economy", "education", "emphasis", "equality",
    "evidence", "evolution", "excellence", "expansion", "experience",
    "exploration", "expression", "fairness", "feedback", "fluency",
    "freedom", "generosity", "guidance", "harmony", "heritage",
    "humility", "identity", "inclusion", "influence", "innovation",
    "integrity", "judgment", "knowledge", "language", "leadership",
    "learning", "leverage", "loyalty", "mastery", "meaning",
    "momentum", "narrative", "network", "openness", "opportunity",
    "outcome", "ownership", "patience", "planning", "precision",
    "principle", "priority", "progress", "purpose", "quality",
    "resilience", "resource", "respect", "responsibility", "revenue",
    "security", "sensitivity", "simplicity", "solution", "strategy",
    "structure", "success", "sustainability", "thinking", "tolerance",
    "transition", "transparency", "trust", "understanding", "unity",
    "urgency", "utility", "version", "versatile", "viewpoint",
    "willingness", "wisdom", "workflow", "workspace", "worldview",
    "abandon", "absorb", "achieve", "acquire", "activate",
    "adapt", "address", "advance", "advocate", "affect",
    "allocate", "amplify", "analyze", "anchor", "apply",
    "approach", "arrange", "assemble", "assess", "assign",
    "assume", "attach", "attend", "attract", "audit",
    "automate", "balance", "benchmark", "brainstorm", "broadcast",
    "budget", "capture", "categorize", "channel", "clarify",
    "classify", "collaborate", "collect", "combine", "commit",
    "compare", "compile", "complete", "compress", "compute",
    "configure", "connect", "consider", "construct", "consult",
    "convert", "coordinate", "create", "customize", "delegate",
    "deliver", "deploy", "design", "detect", "develop",
    "diagnose", "discover", "display", "distribute", "document",
    "enable", "encode", "enforce", "enhance", "establish",
    "evaluate", "execute", "expand", "explain", "explore",
    "extract", "facilitate", "filter", "finalize", "format",
    "generate", "govern", "handle", "identify", "implement",
    "improve", "include", "increase", "install", "measure",
    "migrate", "minimize", "monitor", "organize", "produce",
    "protect", "publish", "recover", "reduce", "refactor",
    "release", "render", "replace", "report", "request",
    "resolve", "retrieve", "review", "schedule", "secure",
    "segment", "select", "simulate", "specify", "submit",
    "support", "synchronize", "transfer", "transform", "update",
    "upgrade", "validate", "verify", "visualize", "wrapper"
];

export const hardWords = [
    "rhythm", "queue", "conscientious", "maintenance", "occurrence", "schadenfreude", "vicissitude", "abbreviate",
    "accidentally", "accommodate", "achievement", "acknowledge", "acquaintance", "acquire", "advisable",
    "aggressive", "allegiance", "alphabet", "annihilate", "anonymous", "apparent", "appearance", "appropriate",
    "argument", "arrangement", "ascertain", "assassination", "associate", "attendance", "audience", "auxiliary",
    "barbecue", "bargain", "basically", "beautiful", "beginning", "belligerent", "benefited", "biscuit",
    "boundary", "business", "calendar", "camouflage", "campaign", "candidate", "caribbean", "category",
    "cemetery", "challenge", "changeable", "characteristic", "circuit", "circumstance", "civilization", "committee",
    "comparative", "competent", "completely", "concede", "conceivable", "condemn", "condescend", "conscience",
    "consciousness", "consistent", "continuous", "controlled", "controversial", "convenience", "corollary", "correspondence",
    "council", "counsel", "counterfeit", "courageous", "courteous", "criticism", "criticize", "deferred",
    "definitely", "definition", "dependent", "desperate", "deterrent", "disappear", "disappoint", "disastrous",
    "discipline", "efficient", "eighth", "eligible", "eliminate", "embarrass", "eminent", "emphasize",
    "endeavor", "enthusiasm", "entrepreneur", "environment", "equipped", "equivalent", "especially", "exaggerate",
    "existence", "experience", "explanation", "familiar", "foreign", "forty", "fourth", "government", "grammar", "guarantee",
    "hierarchy", "idiosyncrasy", "illusory", "impeccable", "impetus", "incendiary", "incredulous", "indignation", "inevitable", "infallible",
    "inscrutable", "insidious", "instigate", "intangible", "intellectual", "intermittent", "introspection", "irrelevant", "juxtapose",
    "legitimate", "leniency", "lethargy", "levitation", "lucidity", "magnify", "malevolent", "mendacity", "meticulous", "mitigate",
    "negligible", "nostalgia", "notorious", "nuance", "oblivious", "obsequious", "obstinate", "omniscient", "onerous", "opulence",
    "panorama", "paradigm", "paradoxical", "peculiar", "pedantic", "penchant", "perennial", "perfunctory", "peripheral", "persuasion",
    "pertinent", "philanthropy", "plausible", "plethora", "polarize", "precarious", "prelude", "prerogative", "proclivity", "prodigious",
    "abhorrent", "abominable", "absolution", "abstinence", "abundance", "accelerate", "accidental", "acclimate", "accomplice", "accountable",
    "accusation", "acquittal", "admonition", "adversarial", "affidavit", "affirmation", "aggravated", "allegation", "alleviate", "alliterate",
    "amalgamate", "ambiguity", "ameliorate", "amorphous", "anachronism", "anecdote", "annex", "antagonize", "anticipate", "antiquated",
    "apathetic", "aplenty", "appreciate", "apprehend", "arbitrate", "aristocrat", "articulate", "aspiration", "assiduous", "atrocious",
    "audacious", "auspicious", "authoritative", "autonomous", "avoidance", "bewildering", "blatant", "boisterous", "bureaucracy", "candid",
    "catastrophic", "causation", "charismatic", "circumvent", "collaborate", "combustion", "commemorate", "compatible", "compelling", "competence",
    "complacent", "complicated", "comprehensive", "conceited", "conclusive", "condescending", "congruent", "conjecture", "connotation", "consequence",
    "considerate", "conspiracy", "contention", "contradiction", "conviction", "credulous", "cumbersome", "cynicism", "deception", "declaration",
    "deliberate", "delinquent", "demeanor", "democratic", "denounce", "deprivation", "desolate", "determination", "devastation", "devotion",
    "diligence", "dimension", "directives", "discrepancy", "disdainful", "distortion", "divergence", "dominant", "dramatize", "duplicitous",
    "eloquent", "empower", "encourage", "endurance", "enmity", "enlighten", "entitlement", "enumerate", "ephemeral", "erroneous",
    "etiquette", "evasion", "evident", "exorbitant", "expressive", "extensive", "exuberant", "fabricate", "facilitate", "ferocious",
    "fictional", "fiercely", "flamboyant", "fluctuate", "formidable", "fortitude", "fruitless", "fundamental", "futility", "generous",
    "gluttony", "gratitude", "grievance", "grotesque", "grudgingly", "harshness", "hesitant", "humiliate", "hypocrite", "imminent",
    "impartial", "impetuous", "inaccurate", "inadequate", "incentive", "incredibility", "inefficiency", "inequitable", "influence", "ingenuity",
    "initiative", "innocuous", "insatiable", "intensity", "intricate", "irrational", "isolation", "laborious", "lamenting", "lecherous",
    "liberation", "licentious", "limitless", "loathsome", "longstanding", "ludicrous", "magnanimous", "majestic", "manipulative", "mediocre"
];

export const superHardWords = [
    "acumen", "anomaly", "antipathy", "arcane", "assiduous", "cacophony", "cajole", "capricious", "castigate", "chicanery",
    "cogent", "conflagration", "conundrum", "deleterious", "demagogue", "desiccated", "diatribe", "didactic", "diffident", "disparate",
    "ebullient", "effrontery", "egregious", "enervate", "ephemeral", "equanimity", "erudite", "esoteric", "exculpate", "exigent",
    "facetious", "fastidious", "fatuous", "garrulous", "gregarious", "hackneyed", "hapless", "harangue", "hegemony", "iconoclast",
    "idiosyncratic", "impecunious", "impetuous", "implacable", "inchoate", "indefatigable", "ineffable", "inexorable", "ingenuous", "inimical",
    "insipid", "intransigent", "inure", "invective", "inveterate", "jovial", "laconic", "lassitude", "lethargic", "loquacious",
    "magnanimous", "malediction", "malleable", "maverick", "mendacious", "mercurial", "modicum", "multifarious", "nefarious", "neophyte",
    "obdurate", "obfuscate", "obstreperous", "officious", "ostentatious", "palliate", "panacea", "paradigmatic", "pariah",
    "paucity", "pejorative", "pellucid", "penury", "perfidious", "pernicious", "perspicacious", "phlegmatic", "platitude",
    "polemic", "precocious", "prescient", "probity", "promulgate", "propensity", "puerile", "pugnacious",
    "quiescent", "recalcitrant", "redolent", "sagacious", "salubrious", "sanguine", "solipsism", "spurious", "strident", "subservient",
    "suffrage", "supercilious", "sycophant", "taciturn", "tantamount", "tempestuous", "terse", "torpor", "transient", "trenchant",
    "ubiquitous", "unctuous", "vacillate", "venerable", "verbose", "vicarious", "vindicate", "virtuoso", "viscous",
    "vituperative", "vociferous", "wane", "wistful", "zealous", "zeitgeist", "zenith", "zeugma",
    "ameliorate", "anathema", "antediluvian", "apocryphal", "approbation", "arduous", "aspersions", "attenuate",
    "abscond", "acrimony", "adulation", "aesthetic", "agnostic", "alacrity", "alienation", "allegory", "altruistic", "ambivalent",
    "anachronistic", "anarchy", "anecdotal", "anthropic", "antithesis", "apathy", "apostle", "appease", "ardor", "artisan",
    "ascetic", "atonement", "attrition", "austerity", "avarice", "axiom", "belated", "belie", "benevolent", "berate",
    "bestow", "bewitch", "blithe", "brazen", "candor", "catharsis", "censure", "chagrin", "charlatan", "churlish",
    "circumspect", "clemency", "cliche", "coerce", "condone", "contentious", "contrition", "corroborate", "credence", "culpable",
    "debunk", "decadent", "deign", "demerit", "denounce", "deprecate", "deride", "despondent", "devout", "dexterous",
    "diligent", "discern", "disdain", "dissent", "dogmatic", "dormant", "draconian", "duplicity", "elusive", "embellish",
    "emulate", "enigma", "eradicate", "evasive", "exasperate", "exemplary", "exonerate", "expedient", "fallacy", "fervent",
    "fickle", "flagrant", "flounder", "foment", "forbearance", "forthright", "furtive", "garnish", "gloat", "grievous",
    "guile", "hyperbole", "hypothetical", "immutable", "impasse", "impugn", "inadvertent", "incite", "indolent", "inept",
    "inflammatory", "inherent", "innocuous", "insidious", "intrepid", "inundate", "irrevocable", "lament", "languid", "lavish",
    "lax", "levity", "lofty", "loathe", "lucid", "lurid", "malice", "meager", "meander", "mirth",
    "mitigate", "mundane", "naïve", "nebulous", "nonchalant", "nullify", "obscure", "obstinate", "ominous", "orthodox",
    "ostracize", "paradox", "partisan", "pathetic", "patronize", "pensive", "perfidy", "persevere", "petulant", "pilfer",
    "placid", "poignant", "pompous", "pragmatic", "precarious", "predilection", "presumptuous", "prevail", "prodigal", "provocative",
    "prudent", "qualm", "querulous", "quixotic", "rancor", "rapacious", "reconcile", "rectify", "refute", "relentless",
    "renounce", "reprehensible", "resilient", "reticent", "revile", "rhetorical", "rueful", "ruthless", "sanctimonious", "sardonic",
    "scrupulous", "serendipity", "shrewd", "skeptical", "slander", "solemn", "somber", "specious", "stagnant", "steadfast",
    "stifle", "stoic", "subjugate", "submissive", "subtle", "succumb", "sullen", "supple", "surreal", "tenacious",
    "tentative", "thwart", "timid", "truculent", "turbulent", "tyrannical", "unscrupulous", "usurp", "vague", "vehement",
    "vengeance", "veracious", "vindictive", "virulent", "vitriolic", "volatile", "voracious", "vulnerable", "wrath", "zealotry"
];

export const insaneWords = [
    "absquatulate", "adscititious", "anfractuosity", "asphyxiate", "autochthonous", "balderdash", "bibliopole", "bumfuzzle", "cachinnate", "callipygian",
    "canoodle", "catoptromancy", "cockalorum", "collywobbles", "comeuppance", "concupiscent", "cruciverbalist", "curglaff", "dehiscent",
    "dendrochronology", "desideratum", "discombobulate", "donnybrook", "dowsabel", "ecdysiast", "effervescent", "elucubrate", "epistemology", "erythrophobia",
    "esculent", "exsanguinate", "flabbergasted", "flummoxed", "gaberlunzie", "gardyloo", "gastronome", "glabrous", "gobbledygook",
    "grandiloquent", "gumshoe", "haberdashery", "hagiography", "honorificabilitudinitatibus", "hornswoggle", "hullabaloo", "hypnagogic",
    "ignominious", "imbroglio", "impignorate", "inanition", "infundibuliform", "ingurgitate", "inspissate", "interdigitate", "jentacular",
    "kerfuffle", "lackadaisical", "lambaste", "leptosomatic", "logorrhea", "lollygag", "lucubration", "lycanthropy", "macaronic",
    "malarkey", "metathesis", "miscreant", "mountebank", "nincompoop", "obnubilate", "onomatopoeia", "opsimath",
    "palaver", "panjandrum", "paraphernalia", "pastiche", "peradventure", "persnickety", "pettifogger", "philistine", "phyllotaxy", "pizzicato",
    "pleonasm", "polyglot", "prestidigitation", "propinquity", "qualtagh", "quarrelsome", "quiddity", "quixotic", "ragamuffin", "rapscallion",
    "raspberry", "recherché", "recumbent", "refulgent", "regicide", "reminisce", "repercussion", "rigmarole", "risible", "rodomontade",
    "rumination", "saccade", "sacrilege", "samaritan", "sanguinary", "saturnine", "scintilla", "scrofulous", "serendipity",
    "sesquipedalian", "simulacrum", "skulduggery", "slapdash", "sobriquet", "somnambulist", "spelunker", "spuriousness", "stalwart",
    "stipulate", "stratagem", "stupendous", "substantive", "succinct", "supererogatory", "surreptitious",
    "susurration", "sybaritic", "sylvan", "symbiosis", "synesthesia", "taciturnity", "talisman", "tantivy", "tegument",
    "abecedarian", "abnegation", "abscission", "abstemious", "acanthus", "acarpous", "acciaccatura", "accismus", "accoutrements", "acerbic",
    "acervate", "achromatic", "acridity", "acrimoniousness", "aculeate", "adumbrate", "adventitious", "aegrotat", "aeolian", "aesthetic",
    "agathokakological", "agglomeration", "agnomen", "agoraphobia", "agrestic", "aleatoric", "alembic", "algid", "algolagnia", "alieniloquy",
    "aliquot", "alkalescent", "allobrogical", "allochthonous", "alluvion", "alodium", "altiloquence", "altricial", "amanuensis", "amaranthine",
    "ambage", "ambsace", "amentia", "amnicolist", "amphibology", "amphigouri", "amphiloquy", "anacoluthon", "anacreontic", "anadiplosy",
    "anamorphosis", "anaptyxis", "anastrophe", "anathematize", "angiogenesis", "anguilliform", "anhedonia", "animadversion", "annular", "antapology",
    "antonomasia", "aphelion", "apocope", "apophenia", "apophthegm", "aposiopes", "apotropaic", "appoggiatura", "apsidal", "arachibutyrophobia",
    "archiloquy", "argot", "ariolation", "aristarchy", "armigerous", "arrhenotoky", "ascendancy", "aspergillum", "aspersion", "asportation",
    "asseverate", "assiduousness", "astriction", "astrobleme", "atavism", "atelophobia", "atrabiliousness", "attrition", "auscultation", "autocthony",
    "autophobia", "autotelic", "auxological", "avunculocal", "ayah", "azoic", "babracot", "bagatelle", "balneology", "bardolatry",
    "bathysphere", "bathykolpian", "bedlam", "bedraggled", "belomancy", "benthic", "biblioclasm", "bibliothecary", "bicephalous", "bifurcation",
    "bilingualism", "bioluminescent", "biomorphic", "bioptic", "birdlore", "bivouac", "blatherskite", "bleary", "bombilate", "borborygmus",
    "brachylogy", "bradycardia", "brattish", "buccal", "bucolic", "bulimic", "bumbershoot", "cacodemon", "cacoethes", "cacodoxy",
    "cacogeusia", "cacology", "cacosmia", "cadaverous", "caginess", "calenture", "caliginous", "callithump", "callosity", "camelopard",
    "campanology", "cantharidin", "capitulate", "caprification", "captious", "carbuncle", "carmagnole", "carnassial", "catafalque", "catamaran",
    "cataphrenia", "catchpenny", "catoptric", "cavernulous", "cecity", "celerity", "cenotaph", "cephalic", "chrestomathy", "chrematistics",
    "chrysography", "chthonic", "cicatrize", "cimmerian", "circumlocution", "circumvallation", "clangorous", "clandestinity", "claustrophilia", "clerisy",
    "coadjutant", "codicil", "colporteur", "comeliness", "concatenate", "condign", "conurbation", "coprolalia", "cornucopia", "coruscate",
    "costive", "countermand", "crepuscular", "crystallomancy", "culpability", "cupidity", "curmudgeon", "curtilage", "dactylology", "daedal",
    "daemonology", "defalcation", "defenestration", "deictic", "delectation", "deleterious", "demimonde", "demotic", "denticulate", "deracinate",
    "descry", "desultory", "diaphanous", "diastrophism", "diatessaron", "diatonic", "didapper", "diglot", "digressive", "dilapidation",
    "dilettante", "discomfiture", "disconcert", "discursive", "disingenuous", "disputatious", "dissimulate", "distichous", "divagate", "dolmen",
    "doppelganger", "doryphore", "draconine", "dyspeptic", "ebullition", "ecdysis", "edacious", "effete", "effulgent", "effluvium",
    "egalitarian", "egotism", "egregore", "eldritch", "elegy", "emollient", "empyrean", "encomiast", "encomium", "enervation",
    "enigmatic", "ennui", "entelechy", "ephemeron", "epigone", "epiphany", "epistle", "equivocate", "eristic", "errantry",
    "eschatology", "estivation", "etiolate", "etiology", "eudaemonia", "euphonious", "excoriate", "execrable", "exegesis", "exiguous"
];

export const crazyWords = [
    "synecdoche", "trichotillomania", "palaeontology", "daguerreotype", "bougainvillea", "chrysanthemum", "rhododendron", "worcestershire",
    "ichthyosaurus", "erythropoietin", "glossolalia", "hyperbilirubinemia", "onychophagy", "pachycephalosaurus", "quattuordecillion", "staphylococci", "uvulopalatopharyngoplasty",
    "xenotransplantation", "otorhinolaryngological", "otorhinolaryngology", "microseismograph", "psychopharmacology", "spectrophotofluorometer",
    "heterogeneousness", "multidisciplinary", "otoacousticemissions", "cytoskeletal", "metalloproteinase", "osteoarchaeology",
    "zoogeographical", "prognostication", "thermoelectromotive", "ultramicroscopic", "microphotography", "radiopharmaceutical",
    "neuroendocrinological", "psychoneuroimmunology", "pharmacokinetics", "deoxyribonucleic", "mitochondrially", "glycosaminoglycan",
    "electrochemiluminescence", "spectrofluorimetry", "fluorochrome", "bioluminescence", "thermochronology", "pseudomorphically",
    "anthropomorphize", "chorioallantoic", "encephalomyelitis", "hyperparathyroidism", "subterranean", "electroretinogram", "microangiopathy",
    "chromatographically", "ultracentrifugation", "phosphatidylethanolamine", "lymphadenopathy", "pachydermatous", "sphygmomanometer",
    "electrocardiographically", "magnetoencephalography",
    "otorhinolaryngologist", "ultramicroscopy", "thermodynamics", "thermochemistry", "spectrophotometer", "radiotelemetry", "psychophysiology", "neurochemistry", "neuropsychology", "microelectrode",
    "macrocephalus", "lithotripsy", "keratinocyte", "immunodeficiency", "heterozygosity", "gastroenterology", "gastrointestinal", "electrophoresis", "electrostatics", "ectothermic",
    "crystallography", "chronobiology", "chemotherapeutic", "carboxylation", "calcitonin", "bronchoscopy", "biotransformation", "bioavailability", "bibliography",
    "autophagy", "astrophysical", "angiogenesis", "angiosperm", "anamorphosis", "allosteric", "amortization", "amphibious", "antithetical",
    "anthropological", "anticonvulsant", "antisymmetric", "apoptosis", "arachnophobia", "arteriosclerosis", "astrochemistry", "autobiographical", "auxotrophic",
    "abdominalgia", "abdominoplasty", "ablutophobia", "achondroplasia", "achromatopsia", "acroosteolysis", "acromegaly", "actinobacillosis", "adenocarcinoma", "adenohypophysis",
    "adipocytokines", "adrenoleukodystrophy", "agammaglobulinemia", "agoraphobic", "agranulocytosis", "agyrophobia", "albuminuria", "aldosteronism", "alloimmunization", "alveoloplasty",
    "amyloidogenesis", "ancylostomiasis", "androcephalous", "anejaculation", "anesthesiologist", "angioedema", "ankylospondylitis", "anthropomorphism", "antiphospholipid", "antiserotonin",
    "aortocoronary", "aphrodisiomaniac", "apicoectomy", "apneustic", "appendectomy", "appendicularia", "aquathermalism", "archaeopterygian", "archimandrite", "arteriovenous",
    "arthrocentesis", "articulatoriness", "asceticism", "aspermatogenesis", "asthenosphere", "astronautical", "ateliosis", "atherosclerotic", "athetosis", "atmospherical",
    "atrioventricular", "atrochromatic", "audiometry", "autoimmunology", "autonomic", "bacteriophagic", "ballistocardiogram", "baroreceptor", "basophilia", "bathochromic",
    "benzodiazepine", "bioluminescence", "bioinformatics", "biparietal", "brachycephalic", "bradyarrhythmia", "bronchiectasis", "bronchodilator", "bursectomy", "calcinosis",
    "carcinoembryonic", "cardiomegaly", "cardiothoracic", "catecholaminergic", "cephalometric", "cerebrovascular", "chemoreceptors", "cholinesterase", "chromatolysis", "chronotropic",
    "circumferential", "claviculectomy", "cochleotomy", "colonoscopy", "costochondritis", "craniopharyngioma", "crosslinkage", "cystosarcoma", "dacryoadenitis", "decortication",
    "deoxygenation", "dermatomyositis", "dialysability", "diencephalic", "diplopia", "disaccharidase", "dissociative", "ductoscopy", "dysautonomia", "dysmenorrhea",
    "ectodermal", "electrodessication", "electrogastrogram", "embouchure", "embryogenesis", "emphysematous", "encephalography", "endocrinopathy", "endodontics", "enteropathic",
    "epicanthoplasty", "epiglottectomy", "episcleral", "erythematosus", "esophagectomy", "estrogen", "exostosis", "extravasation", "fasciotomy", "fibromyalgia",
    "fluoroscopy", "folliculitis", "gastrectomy", "gastroenteritis", "gastroparesis", "genitourinary", "glioblastoma", "glomerulosclerosis", "glyconeogenesis", "gonorrhea",
    "gynecomastia", "hemarthrosis", "hematomyelia", "hematopathology", "hemiplegia", "hepatocellular", "heteromorphic", "histocompatibility", "homeostasis", "hydronephrosis",
    "hypercoagulability", "hypercortisolism", "hyperkalemia", "hyperlipidemia", "hyperventilation", "hypocalcemia", "hypoglycemia", "hypomagnesemia", "hypothyroidism", "hypoxemia"
];

export const longWords = [
    "pneumonoultramicroscopicsilicovolcanoconiosis",
    "hippopotomonstrosesquippedaliophobia",
    "supercalifragilisticexpialidocious",
    "pseudopseudohypoparathyroidism",
    "floccinaucinihilipilification",
    "antidisestablishmentarianism",
    "honorificabilitudinitatibus",
    "thyroparathyroidectomized",
    "dichlorodiphenyltrichloroethane",
    "llanfairpwllgwyngyllgogerychwyrndrobwllllantysiliogogogoch",
    "spectrophotofluorometrically",
    "psychoneuroendocrinological",
    "radioimmunoelectrophoresis",
    "taumatawhakatangihangakoauauotamateaturipukakapikimaungahoronukupokaiwhenuakitanatahu",
    "aequeosalinocalcalinoceraceoaluminosocupreovitriolic",
    "bababadalgharaghtakamminarronnkonnbronntonnerronntuonnthunntrovarrhounawnskawntoohoohoordenenthurnuk",
    "chargoggagoggmanchauggagoggchaubunagungamaugg",
    "osseocarnisanguineoviscericartilaginonervomedullary",
    "trinitrophenylmethylnitramine",
    "paraaminobenzenesulfonamide",
    "hepaticocholangiostomy",
    "tetramethyldiaminobenzhydrol",
    "overintellectualization",
    "counterrevolutionary",
    "incomprehensibilities",
    "disproportionableness",
    "microspectrophotometer",
    "immunohistochemistry",
    "electroencephalography",
    "paleomagnetism",
    "paleobiogeography",
    "extraterritoriality",
    "compartmentalization",
    "institutionalization",
    "professionalization",
    "decriminalization",
    "industrialization",
    "democratization",
    "hypercholesterolemia",
    "thrombocytopenia",
    "cardiomyopathy",
    "atherosclerosis",
    "encephalopathy",
    "glomerulonephritis",
    "lymphogranulomatosis",
    "histoplasmosis",
    "blastomycosis",
    "coccidioidomycosis",
    "cryptococcosis",
    "paracoccidioidomycosis",
    "aspergillosis",
    "zygomycosis",
    "phaeohyphomycosis",
    "dermatophytosis",
    "onychomycosis",
    "trichomoniasis",
    "giardiasis",
    "leishmaniasis",
    "trypanosomiasis",
    "schistosomiasis",
    "echinococcosis",
    "cysticercosis",
    "paragonimiasis",
    "clonorchiasis",
    "opisthorchiasis",
    "fascioliasis",
    "fasciolopsiasis",
    "strongyloidiasis",
    "trichuriasis",
    "ascariasis",
    "enterobiasis",
    "anisakiasis",
    "toxocariasis",
    "baylisascariasis",
    "gnathostomiasis",
    "capillariasis",
    "trichinellosis",
    "dracunculiasis",
    "onchocerciasis",
    "loiasis",
    "mansonelliasis",
    "dirofilariasis",
    "lymphangiectasia",
    "telangiectasia",
    "angiosarcoma",
    "hemangiopericytoma",
    "rhabdomyosarcoma",
    "leiomyosarcoma",
    "liposarcoma",
    "osteosarcoma",
    "chondrosarcoma",
    "fibrosarcoma",
    "neurofibrosarcoma",
    "retinoblastoma",
    "nephroblastoma",
    "hepatoblastoma",
    "pancreatoblastoma",
    "pleuropulmonary",
    "pseudohypoparathyroidism",
    "electrocardiographically",
    "nonestablishmentarianism",
    "interdenominationalism",
    "superintellectualization",
    "incomprehensibility",
    "oversimplification",
    "deindustrialization",
    "reindustrialization",
    "redemocratization",
    "laryngotracheobronchitis",
    "eellogofusciouhipoppokunurious",
    "hexakosioihexekontahexaphobia",
    "donaudampfschifffahrtselektrizitatenhauptbetriebswerkbauunterbeamtengesellschaft",
    "duadecodunoscopy",
    "electroencephalographically", "psychoneuroimmunological", "microphotographic", "neuroendocrinological", "spectrophotofluorometrical",
    "immunohistochemically", "radiopharmaceuticals", "ultracentrifugational", "chromatographically", "microangiopathies",
    "gastroenterological", "cardiothoracic", "bronchopulmonary", "rhinolaryngological", "otorhinolaryngological", "ophthalmological",
    "neurophysiological", "psychopharmacological", "electrophysiological", "electromagnetically",
    "transubstantiation", "incompatibilities", "mischaracterization", "overcommercialization", "reconceptualization",
    "deinstitutionalization", "reprofessionalization", "thyroparathyroidectomies", "sesquipedalianism",
    "pseudopseudohypoparathyroidisms", "antidisestablishmentarianisms", "counterrevolutionaries", "microspectrophotometers", "spectrophotofluorometries",
    "electrocardiographies", "immunohistochemistries", "interdenominationalisms", "decriminalizations", "industrializations",
    "professionalizations", "overintellectualizations", "hypercholesterolemias", "lymphogranulomatoses",
    "gastroenterologicalprocedures", "neuroendocrinologicalstudies", "psychoneuroimmunologicalresearch", "electroencephalographicrecords", "paleomagnetisticalanalysis",
    "abdominoperineal", "acceleromyography", "acetylcholinesterase", "achalasia", "achlorhydria", "acidophilus", "acinetobacter", "adenoidectomy", "adenomatous", "adenosylmethionine",
    "adrenocorticotrophic", "allogeneic", "allotransplantation", "ameloblastoma", "aminotransferase", "amniocentesis", "amphiarthrosis", "amylase", "anaerobiosis", "angioplasty",
    "ankylostomiasis", "appendicostomy", "arteriolosclerosis", "arthroplasty", "atherogenesis", "atrophogenesis", "autoantibodies", "autologous", "bacteriuria", "barotrauma",
    "bicuspidization", "bilirubin", "bioprosthesis", "bisphosphonates", "blastocystis", "blepharoplasty", "bloodbornepathogen", "botulinumtoxin", "brachytherapy", "bronchoalveolar",
    "bursoplasty", "calcification", "carcinosarcoma", "cardiodefibrillator", "cerebrospinal", "chemoimmunotherapy", "chiropractics", "cholangiopancreatography", "cholecystectomy", "chordotomy",
    "chromothripsis", "cicatrization", "circumferential", "cleidocranial", "coagulopathy", "colonoscopy", "conization", "corticotrophin", "cryoablation", "cryotherapy",
    "cutaneousmastocytosis", "cystourethroscopy", "decompensation", "dermatomyositis", "diastereoisomer", "diverticulosis", "dopaminergic", "duodenoscopy", "dysbiosis", "dyspareunia",
    "electroconvulsive", "electromyography", "embolization", "endarterectomy", "endothelialization", "epigastralgia", "erythrocytosis", "esophagogastroduodenoscopy", "fenestration", "fluorodeoxyglucose",
    "gastrointestinal", "glomerulitis", "gonorrhoeae", "granulocytopenia", "hematochezia", "hemodialysis", "hepatosplenomegaly", "hippocampus", "hyperaldosteronism", "hypersensitivity",
    "hysterosalpingography", "immunofluorescence", "immunotherapy", "intervertebral", "intracranial", "intraperitoneal", "ischiorectal", "jejunoileitis", "keratoconus", "laparoscopic",
    "leptomeningeal", "leucocytopenia", "lipodystrophy", "lymphocytosis", "macroadenoma", "mastoidectomy", "mediastinoscopy", "meningoencephalitis", "mesothelioma", "microbiomics",
    "mitochondrial", "mononeuropathy", "mucopolysaccharidosis", "myelodysplasia", "myocarditis", "nasopharyngoscopy", "neurofibromatosis", "neuropathology", "neutropenia", "oculomotor",
    "oligodendroglioma", "ophthalmoscopy", "osteoarthropathy", "osteonecrosis", "otosclerosis", "ovariectomy", "pancreaticoduodenectomy", "pancreatography", "parasitology", "parathyroidectomy"
];

export const impossibleWords = [
    "lopadotemachoselachogaleokranioleipsanodrimhypotrimmatosilphiokarabomelitokatakechymenokichlepikossyphophattoperisteralektryonoptekephalliokigklopeleiolagoiosiraiobaphetraganopterygon",
    "methionylglutaminylarginyltyrosylglutamylserylleucylphenylalanylalanylglutaminylleucyllysylglutamylarginyllysylglutamylglycylalanylphenylalanylvalylprolylphenylalanylvalylthreonylleucylglycylaspartylprolylglycylisoleucylglutamylglutaminylserylleucyllysylisoleucylaspartylthreonylleucylisoleucylglutamylalanylglycylalanylaspartylalanylleucylglutamylleucylglycylisoleucylprolylphenylalanylserylaspartylprolylleucylalanylaspartylglycylprolylthreonylisoleucylglutaminylasparaginylalanylthreonylleucylarginylalanylphenylalanylalanylalanylglycylvalylthreonylprolylalanylglutaminylcysteinylphenylalanylglutamylmethionylleucylalanylleucylisoleucylarginylglutaminyllysylhistidylprolylthreonylisoleucylprolylisoleucylglycylleucylleucylmethionyltyrosylalanylasparaginylleucylvalylphenylalanylasparaginyllysylglycylisoleucylaspartylglutamylphenylalanyltyrosylalanylglutaminylcysteinylglutamyllysylvalylglycylvalylaspartylserylvalylleucylvalylalanylaspartylvalylprolylvalylglutaminylglutamylserylalanylprolylphenylalanylarginylglutaminylalanylalanylleucylarginylhistidylasparaginylvalylalanylprolylisoleucylphenylalanylisoleucylcysteinylprolylprolylaspartylalanylaspartylaspartylaspartylleucylleucylarginylglutaminylisoleucylalanylseryltyrosylglycylarginylglycyltyrosylthreonyltyrosylleucylleucylserylarginylalanylglycylvalylthreonylglycylalanylglutamylasparaginylarginylalanylalanylleucylprolylleucylasparaginylhistidylleucylvalylalanyllysylleucyllysylglutamyltyrosylasparaginylalanylalanylprolylprolylleucylglutaminylglycylphenylalanylglycylisoleucylserylalanylprolylaspartylglutaminylvalyllysylalanylalanylisoleucylaspartylalanylglycylalanylalanylglycylalanylisoleucylserylglycylserylalanylisoleucylvalyllysylisoleucylisoleucylglutamylglutaminylhistidylasparaginylisoleucylglutamylprolylglutamyllysylmethionylleucylalanylalanylleucyllysylvalylphenylalanylvalylglutaminylprolylmethionyllysylalanylalanylthreonylarginylserine",
    "acetylseryltyrosylserylisoleucylthreonylserylprolylserylglutaminylphenylalanylvalylphenylalanylleucylserylserylvalyltryptophylalanylaspartylprolylisoleucylglutamylleucylleucylasparaginylvalylcysteinylthreonylserylserylleucylglycylasparaginylglutaminylphenylalanylglutaminylthreonylglutaminylglutaminylalanylarginylthreonylthreonylglutaminylvalylglutaminylglutaminylphenylalanylserylglutaminylvalyltryptophyllysylprolylphenylalanylprolylglutaminylserylthreonylvalylarginylphenylalanylprolylglycylaspartylvalyltyrosyllysylvalyltyrosylarginyltyrosylasparaginylalanylvalylleucylaspartylprolylleucylisoleucylthreonylalanylleucylleucylglycylthreonylphenylalanylaspartylthreonylarginylasparaginylarginylisoleucylisoleucylglutamylvalylglutamylasparaginylglutaminylglutaminylserylprolylthreonylthreonylalanylglutamylthreonylleucylaspartylalanylthreonylarginylarginylvalylaspartylaspartylalanylthreonylvalylalanylisoleucylarginylserylalanylasparaginylisoleucylasparaginylleucylvalylasparaginylglutamylleucylvalylarginylglycylthreonylglycylleucyltyrosylasparaginylglutaminylasparaginylthreonylphenylalanylglutamylserylmethionylserylglycylleucylvalyltryptophylthreonylserylalanylprolylalanylseryl",
    "methionylthreonylthreonylglutaminylarginyltyrosylglutamylserylleucylphenylalanylalanylglutaminylleucyllysylglutamylarginyllysylglutamylglycylalanylphenylalanylvalylprolylphenylalanylvalylthreonylleucylglycylaspartylprolylglycylisoleucylglutamylglutaminylserylleucyllysylisoleucylaspartylthreonylleucylisoleucylglutamylalanylglycylalanylaspartylalanylleucylglutamylleucylglycylisoleucylprolylphenylalanylserylaspartylprolylleucylalanylaspartylglycylprolylthreonylisoleucylglutaminylasparaginylalanylthreonylleucylarginylalanylphenylalanylalanylalanylglycylvalylthreonylprolylalanylglutaminylcysteinylphenylalanylglutamylmethionylleucylalanylleucylisoleucylarginylglutaminyllysylhistidylprolylthreonylisoleucylprolylisoleucylglycylleucylleucylmethionyltyrosylalanylasparaginylleucylvalylphenylalanylasparaginyllysylglycylisoleucylaspartylglutamylphenylalanyltyrosylalanylglutaminylcysteinylglutamyllysylvalylglycylvalylaspartylserylvalylleucylvalylalanylaspartylvalylprolylvalylglutaminylglutamylserylalanylprolylphenylalanylarginylglutaminylalanylalanylleucylarginylhistidylasparaginylvalylalanylprolylisoleucylphenylalanylisoleucylcysteinylprolylprolylaspartylalanylaspartylaspartylaspartylleucylleucylarginylglutaminylisoleucylalanylseryltyrosylglycylarginylglycyltyrosylthreonyltyrosylleucylleucylserylarginylalanylglycylvalylthreonylglycylalanylglutamylasparaginylarginylalanylalanylleucylprolylleucylasparaginylhistidylleucylvalylalanyllysylleucyllysylglutamyltyrosylasparaginylalanylalanylprolylprolylleucylglutaminylglycylphenylalanylglycylisoleucylserylalanylprolylaspartylglutaminylvalyllysylalanylalanylisoleucylaspartylalanylglycylalanylalanylglycylalanylisoleucylserylglycylserylalanylisoleucylvalyllysylisoleucylisoleucylglutamylglutaminylhistidylasparaginylisoleucylglutamylprolylglutamyllysylmethionylleucylalanylalanylleucyllysylvalylphenylalanylvalylglutaminylprolylmethionyllysylalanylalanylthreonylarginylserine",
    "seryltyrosylserylisoleucylthreonylserylprolylserylglutaminylphenylalanylvalylphenylalanylleucylserylserylvalyltryptophylalanylaspartylprolylysoleucylglutamylleucylleucylasparaginylvalylcysteinylthreonylserylserylleucylglycylasparaginylglutaminylphenylalanylglutaminylthreonylglutaminylglutaminylalanylarginylthreonylthreonylglutaminylvalylglutaminylglutaminylphenylalanylserylglutaminylvalyltryptophyllysylprolylphenylalanylprolylglutaminylserylthreonylvalylarginylphenylalanylprolylglycylaspartylvalyltyrosyllysylvalyltyrosylarginyltyrosylasparaginylalanylvalylleucylaspartylprolylleucylisoleucylthreonylalanylleucylleucylglycylthreonylphenylalanylaspartylthreonylarginylasparaginylarginylisoleucylisoleucylglutamylvalylglutamylasparaginylglutaminylglutaminylserylprolylthreonylthreonylalanylglutamylthreonylleucylaspartylalanylthreonylarginylarginylvalylaspartylaspartylalanylthreonylvalylalanylisoleucylarginylserylalanylasparaginylisoleucylasparaginylleucylvalylasparaginylglutamylleucylvalylarginylglycylthreonylglycylleucyltyrosylasparaginylglutaminylasparaginylthreonylphenylalanylglutamylserylmethionylserylglycylleucylvalyltryptophylthreonylserylalanylprolylalanylserylserylserylserylserylserylseryl",
    "abcdefghijklmnopqrstuvwxyzabcdefghijklmnopqrstuvwxyzabcdefghijklmnopqrstuvwxyzabcdefghijklmnopqrstuvwxyzabcdefghijklmnopqrstuvwxyzabcdefghijklmnopqrstuvwxyzabcdefghijklmnopqrstuvwxyzabcdefghijklmnopqrstuvwxyz",
    "pneumonoultramicroscopicsilicovolcanoconiosispneumonoultramicroscopicsilicovolcanoconiosispneumonoultramicroscopicsilicovolcanoconiosis",
    "supercalifragilisticexpialidocioussupercalifragilisticexpialidocioussupercalifragilisticexpialidocioussupercalifragilisticexpialidocious",
    "titinchemicalnamefullstartmethionylthreonylthreonylglutaminylarginyltyrosylglutamylserylleucylphenylalanylalanylglutaminylleucyllysylglutamylarginyllysylglutamylglycylalanylphenylalanylvalylprolylphenylalanylvalylthreonylleucylglycylaspartylprolylglycylisoleucylglutamylglutaminylserylleucyllysylisoleucylaspartylthreonylleucylisoleucylglutamylalanylglycylalanylaspartylalanylleucylglutamylleucylglycylisoleucylprolylphenylalanylserylaspartylprolylleucylalanylaspartylglycylprolylthreonylisoleucylglutaminylasparaginylalanylthreonylleucylarginylalanylphenylalanylalanylalanylglycylvalylthreonylprolylalanylglutaminylcysteinylphenylalanylglutamylmethionylleucylalanylleucylisoleucylarginylglutaminyllysylhistidylprolylthreonylisoleucylprolylisoleucylglycylleucylleucylmethionyltyrosylalanylasparaginylleucylvalylphenylalanylasparaginyllysylglycylisoleucylaspartylglutamylphenylalanyltyrosylalanylglutaminylcysteinylglutamyllysylvalylglycylvalylaspartylserylvalylleucylvalylalanylaspartylvalylprolylvalylglutaminylglutamylserylalanylprolylphenylalanylarginylglutaminylalanylalanylleucylarginylhistidylasparaginylvalylalanylprolylisoleucylphenylalanylisoleucylcysteinylprolylprolylaspartylalanylaspartylaspartylaspartylleucylleucylarginylglutaminylisoleucylalanylseryltyrosylglycylarginylglycyltyrosylthreonyltyrosylleucylleucylserylarginylalanylglycylvalylthreonylglycylalanylglutamylasparaginylarginylalanylalanylleucylprolylleucylasparaginylhistidylleucylvalylalanyllysylleucyllysylglutamyltyrosylasparaginylalanylalanylprolylprolylleucylglutaminylglycylphenylalanylglycylisoleucylserylalanylprolylaspartylglutaminylvalyllysylalanylalanylisoleucylaspartylalanylglycylalanylalanylglycylalanylisoleucylserylglycylserylalanylisoleucylvalyllysylisoleucylisoleucylglutamylglutaminylhistidylasparaginylisoleucylglutamylprolylglutamyllysylmethionylleucylalanylalanylleucyllysylvalylphenylalanylvalylglutaminylprolylmethionyllysylalanylalanylthreonylarginylserine",
    "qwertyuiopasdfghjklzxcvbnmqwertyuiopasdfghjklzxcvbnmqwertyuiopasdfghjklzxcvbnmqwertyuiopasdfghjklzxcvbnmqwertyuiopasdfghjklzxcvbnmqwertyuiopasdfghjklzxcvbnmqwertyuiopasdfghjklzxcvbnmqwertyuiopasdfghjklzxcvbnm",
    "Nirantarandhakaritadigantarakandaladamandasudharasabindusandrataraghanaghanavrndasandehakarasyandamanamakarandabindubandhurataramakandatarukulatalpakalpamrdulasikatajalajatilamulatalamaruvakamiladalaghulaghulayakalitaramaniyapaniyasalikabalikakararavindagalantikagaladelalavangapatalaghanasarakasturikatisaurabhameduralaghutaramadhurasitalatarasaliladharanirakarisnutadiyavimalavilocanamayukharekhapasaritapipasayasapathikalokan",
    "Nonagintaoctoginseptuaginsexaginquinquaginquadragintriginvigindecillinonagintaoctoginseptuaginsexaginquinquaginquadragintriginvigindecillinonagintaoctoginseptuaginsexaginquinquaginquadragintriginvigindecillinillion",
    "Krungthepmahanakhonamonrattanakosinmahintharayuthayamahadilokphophnoppharatratchathaniburiromudomratchaniwetmahasathanamonpimanawatansathitsakkathattiyawitsanukamprasit",
    "Tweedehandsemotorverkoopsmannevakbondstakingsvergaderingsameroeperstoespraakskrywerspersverklaringuitreikingsmediakonferensieaankondiging",
    "Nalunaarasuartaateeraaranngualioiligeullioqiliffissualioriataallaqqissupilorujussuanngortartuinnakasinngortinniamisaalinnguatsiaraluallaqqooqigaminngamiaasiinngooq",
    "pseudopseudohypoparathyroidism",
    "floccinaucinihilipilification",
    "antidisestablishmentarianism",
    "ultramicroscopicsilicovolcanoconiosis",
    "titin"
];

export const getRandomWord = (mode = 'Normal') => {
    if (mode === 'Easy') return easyWords[Math.floor(Math.random() * easyWords.length)];
    if (mode === 'Wet') return 'wet';
    if (mode === 'Normal') return normalWords[Math.floor(Math.random() * normalWords.length)];
    if (mode === 'Hard') return hardWords[Math.floor(Math.random() * hardWords.length)];
    if (mode === 'Super Hard') return superHardWords[Math.floor(Math.random() * superHardWords.length)];
    if (mode === 'Insane') return insaneWords[Math.floor(Math.random() * insaneWords.length)];
    if (mode === 'Crazy') return crazyWords[Math.floor(Math.random() * crazyWords.length)];
    if (mode === 'Master') return longWords[Math.floor(Math.random() * longWords.length)];
    if (mode === 'Impossible') return impossibleWords[Math.floor(Math.random() * impossibleWords.length)];
    return normalWords[Math.floor(Math.random() * normalWords.length)];
};
