export const easyWords = [
    "cat", "dog", "sun", "run", "jump", "blue", "red", "fast", "slow", "big",
    "small", "tree", "bird", "fish", "book", "pen", "desk", "lamp", "hat", "cap",
    "sky", "star", "moon", "fire", "ice", "hot", "cold", "wet", "dry", "soft",
    "hard", "long", "easy", "kind", "play", "sing", "walk", "talk", "look", "see",
    "hand", "foot", "head", "face", "eye", "ear", "nose", "mouth", "arm", "leg",
    "door", "wall", "floor", "roof", "gate", "road", "park", "lake", "hill", "wind",
    "rain", "snow", "milk", "cake", "pear", "apple", "grape", "box", "bag", "cup",
    "fork", "spoon", "plate", "bowl", "chair", "bed", "ball", "bat", "ship", "boat",
    "car", "bus", "bike", "plane", "train", "gold", "silver", "iron", "rock", "sand",
    "dirt", "leaf", "root", "seed", "rose", "lily", "bell", "drum", "flag", "star",
    // +50 additional easy/common words
  // used chatgpt to make this, too lazy to write all this down
    "milkman", "candy", "pillow", "blanket", "button", "window", "mirror", "clock", "cookie", "shadow",
    "ribbon", "puzzle", "garden", "butter", "cheese", "cookie", "breeze", "candle", "needle", "thread",
    "pocket", "ticket", "magnet", "bagel", "camera", "basket", "helmet", "wallet", "socks", "jacket",
    "sweater", "garden", "tomato", "onion", "banana", "orange", "pepper", "lettuce", "castle", "bridge",
    "island", "harbor", "cottage", "bucket", "ladder", "racket", "pencil", "eraser", "notebook", "staple",
    "magpie", "saddle", "ferry", "lantern", "bottle", "whistle"
];

export const normalWords = [
    "algorithm", "function", "variable", "constant", "iteration", 
    "syntax", "compiler", "debugging", "interface", "protocol",
    "asynchronous", "callback", "promise", "database", "encryption",
    "frontend", "backend", "middleware", "framework", "library",
    "deployment", "repository", "abstraction", "polymorphism", "inheritance",
    "encapsulation", "architecture", "microservice", "container", "virtualization",
    "responsive", "performance", "optimization", "scalability", "accessibility",
    "development", "production", "staging", "environment", "dependency",
    "concurrency", "parallelism", "serialization", "deserialization", "hexadecimal",
    "binary", "boolean", "integer", "string", "character",
    "lightning", "mountain", "keyboard", "strength", "horizon",
    "symphony", "paradox", "velocity", "quantum", "gravity",
    "perspective", "creative", "efficient", "powerful", "dynamic",
    "validation", "authentication", "authorization", "infrastructure", "initialization",
    "documentation", "specification", "implementation", "visualization", "manipulation",
    "configuration", "notification", "registration", "transformation", "translation",
    "computation", "communication", "integration", "navigation", "publication",
    "celebration", "competition", "imagination", "inspiration", "motivation",
    "preparation", "presentation", "recognition", "reflection", "satisfaction",
    "traditional", "fundamental", "substantial", "artificial", "intelligence",
    "blockchain", "cryptography", "distributed", "decentralized", "observation",
    // +50 additional normal-mode words
    "synthesis", "modular", "concurrency", "throughput", "latency", "bandwidth", "middleware",
    "orchestration", "provisioning", "benchmark", "refactor", "backpressure", "idempotent",
    "serialization", "deserialization", "heuristic", "annotation", "immutable", "convention",
    "prototype", "iteration", "heuristics", "monolithic", "observability", "telemetry",
    "profiling", "dependency", "containerize", "rollback", "featureflag", "bluegreen",
    "canary", "endpoint", "payload", "handshake", "compression", "enrichment", "throttling",
    "caching", "replication", "sharding", "partition", "indexing", "normalization",
    "denormalize", "garbagecollected", "scheduler", "mutex", "semaphore", "checkpoint",
    "checkpointing", "transcoding", "provisioner", "safeguard"
];

export const hardWords = [
    "rhythm", "queue", "conscientious", "maintenance", "occurrence", "schadenfreude", "vicissitude", "abbreviate", 
    "accidentally", "accommodate", "achievement", "acknowledge", "acquaintance", "acquire", "adultery", "advisable", 
    "aggressive", "allegiance", "alphabet", "annihilate", "anonymous", "apparent", "appearance", "appropriate", 
    "argument", "arrangement", "ascertain", "assassination", "associate", "attendance", "audience", "auxiliary", 
    "barbecue", "bargain", "basically", "beautiful", "beginning", "belligerent", "benefited", "biscuit", 
    "boundary", "business", "calendar", "camouflage", "campaign", "candidate", "caribbean", "category", 
    "cemetery", "challenge", "changeable", "characteristic", "circuit", "circumstance", "civilization", "committee", 
    "comparative", "competent", "completely", "concede", "conceivable", "condemn", "condescend", "conscience", 
    "consciousness", "consistent", "continuous", "controlled", "controversial", "convenience", "corollary", "correspondence", 
    "council", "counsel", "counterfeit", "courageous", "courteous", "criticism", "criticize", "deferred", 
    "definitely", "definition", "dependent", "desperate", "deterrent", "disappear", "disappoint", "disastrous", 
    "discipline", "efficient", "eighth", "eligible", "eliminate", "embarrass", "eminent", "emphasize", 
    "endeavor", "enthusiasm", "entrepreneur", "environment", "equipped", "equivalent", "especially", "exaggerate",
    "existence", "experience", "explanation", "familiar", "foreign", "forty", "fourth", "government", "grammar", "guarantee",
    // +50 additional hard words
    "hierarchy", "idiosyncrasy", "illusory", "impeccable", "impetus", "incendiary", "incredulous", "indignation", "inevitable", "infallible",
    "infrastructure", "inscrutable", "insidious", "instigate", "intangible", "intellectual", "intermittent", "introspection", "irrelevant", "juxtapose",
    "legitimate", "leniency", "lethargy", "levitation", "lucidity", "magnify", "malevolent", "mendacity", "meticulous", "mitigate",
    "negligible", "nostalgia", "notorious", "nuance", "oblivious", "obsequious", "obstinate", "omniscient", "onerous", "opulence",
    "panorama", "paradigm", "paradoxical", "peculiar", "pedantic", "penchant", "perennial", "perfunctory", "peripheral", "persuasion",
    "pertinent", "philanthropy", "plausible", "plethora", "polarize", "precarious", "prelude", "prerogative", "proclivity", "prodigious"
];

export const superHardWords = [
    "acumen", "anomaly", "antipathy", "arcane", "assiduous", "cacophony", "cajole", "capricious", "castigate", "chicanery",
    "cogent", "conflagration", "conundrum", "deleterious", "demagogue", "desiccated", "diatribe", "didactic", "diffident", "disparate",
    "ebullient", "effrontery", "egregious", "enervate", "ephemeral", "equanimity", "erudite", "esoteric", "exculpate", "exigent",
    "facetious", "fastidious", "fatuous", "garrulous", "gregarious", "hackneyed", "hapless", "harangue", "hegemony", "iconoclast",
    "idiosyncratic", "impecunious", "impetuous", "implacable", "inchoate", "indefatigable", "ineffable", "inexorable", "ingenuous", "inimical",
    "insipid", "intransigent", "inure", "invective", "inveterate", "jovial", "laconic", "lassitude", "lethargic", "loquacious",
    "magnanimous", "malediction", "malleable", "maverick", "mendacious", "mercurial", "modicum", "multifarious", "nefarious", "neophyte",
    "obdurate", "obfuscate", "obsequious", "obstreperous", "officious", "ostentatious", "palliate", "panacea", "paradigmatic", "pariah",
    "paucity", "pejorative", "pellucid", "penury", "perfidious", "perfunctory", "pernicious", "perspicacious", "phlegmatic", "platitude",
    "plethora", "polemic", "precocious", "prescient", "probity", "proclivity", "promulgate", "propensity", "puerile", "pugnacious",
    // +50 additional super-hard words
    "quiescent", "recalcitrant", "redolent", "sagacious", "salubrious", "sanguine", "solipsism", "spurious", "strident", "subservient",
    "suffrage", "supercilious", "sycophant", "taciturn", "tantamount", "tempestuous", "terse", "torpor", "transient", "trenchant",
    "ubiquitous", "unctuous", "vacillate", "venerable", "verbose", "vicarious", "vicissitude", "vindicate", "virtuoso", "viscous",
    "vituperative", "vociferous", "wane", "wistful", "wry", "zealous", "zeitgeist", "zenith", "zeugma", "zoetic",
    "zygotic", "ameliorate", "anathema", "antediluvian", "apocryphal", "approbation", "arduous", "aspersions", "assent", "attenuate"
];

export const insaneWords = [
    "absquatulate", "adscititious", "anfractuosity", "asphyxiate", "autochthonous", "balderdash", "bibliopole", "bumfuzzle", "cachinnate", "callipygian",
    "canoodle", "capnoideous", "catoptromancy", "cockalorum", "collywobbles", "comeuppance", "concupiscent", "cruciverbalist", "curglaff", "dehiscent",
    "dendrochronology", "desideratum", "discombobulate", "donnybrook", "dowsabel", "ecdysiast", "effervescent", "elucubrate", "epistemology", "erythrophobia",
    "esculent", "exsanguinate", "flabbergasted", "flummoxed", "fuddy-duddy", "gaberlunzie", "gardyloo", "gastronome", "glabrous", "gobbledygook",
    "grandiloquent", "gumshoe", "haberdashery", "hagiography", "higgledy-piggledy", "hocus-pocus", "honorificabilitudinitatibus", "hornswoggle", "hullabaloo", "hypnagogic",
    "ignominious", "illatrate", "imbroglio", "impignorate", "inanition", "infundibuliform", "ingurgitate", "inspissate", "interdigitate", "jentacular",
    "kerfuffle", "lackadaisical", "lambaste", "leptosomatic", "limerick", "logorrhea", "lollygag", "lucubration", "lycanthropy", "macaronic",
    "malarkey", "mammothuptich", "metathesis", "miscreant", "mountebank", "namby-pamby", "nincompoop", "obnubilate", "onomatopoeia", "opsimath",
    "palaver", "panjandrum", "paraphernalia", "pastiche", "peradventure", "persnickety", "pettifogger", "philistine", "phyllotaxy", "pizzicato",
    "pleonasm", "polyglot", "prestidigitation", "propinquity", "qualtagh", "quarrelsome", "quiddity", "quixotic", "ragamuffin", "rapscallion",
    // +50 additional insane-mode words
    "raspberry", "recherché", "recumbent", "refulgent", "regicide", "reminisce", "repercussion", "rigmarole", "risible", "rodomontade",
    "rumination", "saccade", "sacrilege", "samaritan", "sandpaper", "sanguinary", "saturnine", "scintilla", "scrofulous", "serendipity",
    "sesquipedalian", "simulacrum", "skulduggery", "slapdash", "sobriquet", "somnambulist", "spectacle", "spelunker", "spuriousness", "stalwart",
    "stickleback", "stipulate", "stonework", "stratagem", "stratified", "stupendous", "substantive", "succinct", "supererogatory", "surreptitious",
    "susurration", "synchronous", "sybaritic", "sylvan", "symbiosis", "synesthesia", "taciturnity", "talisman", "tantivy", "tegument"
];

export const crazyWords = [
    "synecdoche", "sesquipedalian", "trichotillomania", "palaeontology", "daguerreotype", "bougainvillea", "chrysanthemum", "rhododendron", "pfeffernusse", "worcestershire",
    "ichthyosaurus", "erythropoietin", "glossolalia", "hyperbilirubinemia", "onychophagy", "pachycephalosaurus", "quattuordecillion", "staphylococci", "uvulopalatopharyngoplasty",
    "xenotransplantation", "otorhinolaryngological", "otorhinolaryngology", "microseismograph", "psychopharmacology", "spectrophotofluorometer",
    "heterogeneousness", "multidisciplinary", "otoacousticemissions", "cytoskeletal", "metalloproteinase", "osteoarchaeology",
    "zoogeographical", "prognostication", "thermoelectromotive", "ultramicroscopic", "microphotography", "radiopharmaceutical",
    "neuroendocrinological", "psychoneuroimmunology", "pharmacokinetics", "deoxyribonucleic", "mitochondrially", "glycosaminoglycan",
    "electrochemiluminescence", "spectrofluorimetry", "fluorochrome", "bioluminescence", "thermochronology", "pseudomorphically",
    "anthropomorphize", "chorioallantoic", "encephalomyelitis", "hyperparathyroidism", "subterranean", "electroretinogram", "microangiopathy",
    "chromatographically", "ultracentrifugation", "phosphatidylethanolamine", "lymphadenopathy", "pachydermatous", "sphygmomanometer",
    "electrocardiographically", "magnetoencephalography",
    // +50 additional crazy-mode words
    "otorhinolaryngologist", "ultramicroscopy", "thermodynamics", "thermochemistry", "spectrophotometer", "radiotelemetry", "psychophysiology", "neurochemistry", "neuropsychology", "microelectrode",
    "macrocephalus", "lithotripsy", "keratinocyte", "immunodeficiency", "heterozygosity", "gastroenterology", "gastrointestinal", "electrophoresis", "electrostatics", "ectothermic",
    "dysfunctional", "crystallography", "chronobiology", "chemotherapeutic", "carboxylation", "calcitonin", "bronchoscopy", "biotransformation", "bioavailability", "bibliography",
    "autophagy", "astrophysical", "angiogenesis", "angiosperm", "anamorphosis", "ambulatory", "allosteric", "amortization", "amphibious", "antithetical",
    "anthropological", "anticonvulsant", "antisymmetric", "apoptosis", "arachnophobia", "arteriosclerosis", "astrochemistry", "autobiographical", "axolotl", "auxotrophic"
];

export const longWords = [
    "pneumonoultramicroscopicsilicovolcanoconiosis",
    "hippopotomonstrosesquippedaliophobia",
    "supercalifragilisticexpialidocious",
    "pseudopseudohypoparathyroidism",
    "floccinaucinihilipilification",
    "antidisestablishmentarianism",
    "honorificabilitudinitatibus",
    "thyroparathyroidectomized",
    "dichlorodiphenyltrichloroethane",
    "llanfairpwllgwyngyllgogerychwyrndrobwllllantysiliogogogoch",
    "spectrophotofluorometrically",
    "psychoneuroendocrinological",
    "radioimmunoelectrophoresis",
    "taumatawhakatangihangakoauauotamateaturipukakapikimaungahoronukupokaiwhenuakitanatahu",
    "aequeosalinocalcalinoceraceoaluminosocupreovitriolic",
    "bababadalgharaghtakamminarronnkonnbronntonnerronntuonnthunntrovarrhounawnskawntoohoohoordenenthurnuk",
    "chargoggagoggmanchauggagoggchaubunagungamaugg",
    "osseocarnisanguineoviscericartilaginonervomedullary",
    "trinitrophenylmethylnitramine",
    "paraaminobenzenesulfonamide",
    "hepaticocholangiostomy",
    "tetramethyldiaminobenzhydrol",
    "overintellectualization",
    "counterrevolutionary",
    "incomprehensibilities",
    "disproportionableness",
    "microspectrophotometer",
    "immunohistochemistry",
    "electroencephalography",
    "paleomagnetism",
    "paleobiogeography",
    "extraterritoriality",
    "compartmentalization",
    "institutionalization",
    "professionalization",
    "decriminalization",
    "industrialization",
    "democratization",
    "hypercholesterolemia",
    "thrombocytopenia",
    "cardiomyopathy",
    "atherosclerosis",
    "encephalopathy",
    "glomerulonephritis",
    "lymphogranulomatosis",
    "histoplasmosis",
    "blastomycosis",
    "coccidioidomycosis",
    "cryptococcosis",
    "paracoccidioidomycosis",
    "aspergillosis",
    "zygomycosis",
    "phaeohyphomycosis",
    "dermatophytosis",
    "onychomycosis",
    "trichomoniasis",
    "giardiasis",
    "leishmaniasis",
    "trypanosomiasis",
    "schistosomiasis",
    "echinococcosis",
    "cysticercosis",
    "paragonimiasis",
    "clonorchiasis",
    "opisthorchiasis",
    "fascioliasis",
    "fasciolopsiasis",
    "strongyloidiasis",
    "trichuriasis",
    "ascariasis",
    "enterobiasis",
    "anisakiasis",
    "toxocariasis",
    "baylisascariasis",
    "gnathostomiasis",
    "capillariasis",
    "trichinellosis",
    "dracunculiasis",
    "onchocerciasis",
    "loiasis",
    "mansonelliasis",
    "dirofilariasis",
    "lymphangiectasia",
    "telangiectasia",
    "angiosarcoma",
    "hemangiopericytoma",
    "rhabdomyosarcoma",
    "leiomyosarcoma",
    "liposarcoma",
    "osteosarcoma",
    "chondrosarcoma",
    "fibrosarcoma",
    "neurofibrosarcoma",
    "retinoblastoma",
    "nephroblastoma",
    "hepatoblastoma",
    "pancreatoblastoma",
    "pleuropulmonary",
    "pseudohypoparathyroidism",
    "electrocardiographically",
    "nonestablishmentarianism",
    "interdenominationalism",
    "superintellectualization",
    "incomprehensibility",
    "oversimplification",
    "deindustrialization",
    "reindustrialization",
    "redemocratization",
    "super-professionalization",
    "laryngotracheobronchitis",
    "eellogofusciouhipoppokunurious",
    "hexakosioihexekontahexaphobia",
    "donaudampfschifffahrtselektrizitatenhauptbetriebswerkbauunterbeamtengesellschaft",
    "duadecodunoscopy",
    // +50 additional very long/master words
    "electroencephalographically", "psychoneuroimmunological", "microphotographic", "neuroendocrinological", "spectrophotofluorometrical",
    "immunohistochemically", "radiopharmaceuticals", "ultracentrifugational", "chromatographically", "microangiopathies",
    "gastroenterological", "cardiothoracic", "bronchopulmonary", "rhinolaryngological", "otorhinolaryngological", "ophthalmological",
    "neurophysiological", "psychopharmacological", "electrophysiological", "electromagnetically", "thermoelectromotiveforce",
    "transubstantiation", "incompatibilities", "mischaracterization", "overcommercialization", "reconceptualization",
    "deinstitutionalization", "reprofessionalization", "ultramicroscopicsilicovolcanoconioses", "thyroparathyroidectomies", "sesquipedalianism",
    "pseudopseudohypoparathyroidisms", "antidisestablishmentarianisms", "counterrevolutionaries", "microspectrophotometers", "spectrophotofluorometries",
    "electrocardiographies", "immunohistochemistries", "interdenominationalisms", "decriminalizations", "industrializations",
    "professionalizations", "overintellectualizations", "hypercholesterolemias", "lymphogranulomatoses", "osteomyelitiscomplications",
    "gastroenterologicalprocedures", "neuroendocrinologicalstudies", "psychoneuroimmunologicalresearch", "electroencephalographicrecords", "paleomagnetisticalanalysis"
];

export const impossibleWords = [
    "lopadotemachoselachogaleokranioleipsanodrimhypotrimmatosilphiokarabomelitokatakechymenokichlepikossyphophattoperisteralektryonoptekephalliokigklopeleiolagoiosiraiobaphetraganopterygon",
    "methionylglutaminylarginyltyrosylglutamylserylleucylphenylalanylalanylglutaminylleucyllysylglutamylarginyllysylglutamylglycylalanylphenylalanylvalylprolylphenylalanylvalylthreonylleucylglycylaspartylprolylglycylisoleucylglutamylglutaminylserylleucyllysylisoleucylaspartylthreonylleucylisoleucylglutamylalanylglycylalanylaspartylalanylleucylglutamylleucylglycylisoleucylprolylphenylalanylserylaspartylprolylleucylalanylaspartylglycylprolylthreonylisoleucylglutaminylasparaginylalanylthreonylleucylarginylalanylphenylalanylalanylalanylglycylvalylthreonylprolylalanylglutaminylcysteinylphenylalanylglutamylmethionylleucylalanylleucylisoleucylarginylglutaminyllysylhistidylprolylthreonylisoleucylprolylisoleucylglycylleucylleucylmethionyltyrosylalanylasparaginylleucylvalylphenylalanylasparaginyllysylglycylisoleucylaspartylglutamylphenylalanyltyrosylalanylglutaminylcysteinylglutamyllysylvalylglycylvalylaspartylserylvalylleucylvalylalanylaspartylvalylprolylvalylglutaminylglutamylserylalanylprolylphenylalanylarginylglutaminylalanylalanylleucylarginylhistidylasparaginylvalylalanylprolylisoleucylphenylalanylisoleucylcysteinylprolylprolylaspartylalanylaspartylaspartylaspartylleucylleucylarginylglutaminylisoleucylalanylseryltyrosylglycylarginylglycyltyrosylthreonyltyrosylleucylleucylserylarginylalanylglycylvalylthreonylglycylalanylglutamylasparaginylarginylalanylalanylleucylprolylleucylasparaginylhistidylleucylvalylalanyllysylleucyllysylglutamyltyrosylasparaginylalanylalanylprolylprolylleucylglutaminylglycylphenylalanylglycylisoleucylserylalanylprolylaspartylglutaminylvalyllysylalanylalanylisoleucylaspartylalanylglycylalanylalanylglycylalanylisoleucylserylglycylserylalanylisoleucylvalyllysylisoleucylisoleucylglutamylglutaminylhistidylasparaginylisoleucylglutamylprolylglutamyllysylmethionylleucylalanylalanylleucyllysylvalylphenylalanylvalylglutaminylprolylmethionyllysylalanylalanylthreonylarginylserine",
    "acetylseryltyrosylserylisoleucylthreonylserylprolylserylglutaminylphenylalanylvalylphenylalanylleucylserylserylvalyltryptophylalanylaspartylprolylisoleucylglutamylleucylleucylasparaginylvalylcysteinylthreonylserylserylleucylglycylasparaginylglutaminylphenylalanylglutaminylthreonylglutaminylglutaminylalanylarginylthreonylthreonylglutaminylvalylglutaminylglutaminylphenylalanylserylglutaminylvalyltryptophyllysylprolylphenylalanylprolylglutaminylserylthreonylvalylarginylphenylalanylprolylglycylaspartylvalyltyrosyllysylvalyltyrosylarginyltyrosylasparaginylalanylvalylleucylaspartylprolylleucylisoleucylthreonylalanylleucylleucylglycylthreonylphenylalanylaspartylthreonylarginylasparaginylarginylisoleucylisoleucylglutamylvalylglutamylasparaginylglutaminylglutaminylserylprolylthreonylthreonylalanylglutamylthreonylleucylaspartylalanylthreonylarginylarginylvalylaspartylaspartylalanylthreonylvalylalanylisoleucylarginylserylalanylasparaginylisoleucylasparaginylleucylvalylasparaginylglutamylleucylvalylarginylglycylthreonylglycylleucyltyrosylasparaginylglutaminylasparaginylthreonylphenylalanylglutamylserylmethionylserylglycylleucylvalyltryptophylthreonylserylalanylprolylalanylseryl",
    "methionylthreonylthreonylglutaminylarginyltyrosylglutamylserylleucylphenylalanylalanylglutaminylleucyllysylglutamylarginyllysylglutamylglycylalanylphenylalanylvalylprolylphenylalanylvalylthreonylleucylglycylaspartylprolylglycylisoleucylglutamylglutaminylserylleucyllysylisoleucylaspartylthreonylleucylisoleucylglutamylalanylglycylalanylaspartylalanylleucylglutamylleucylglycylisoleucylprolylphenylalanylserylaspartylprolylleucylalanylaspartylglycylprolylthreonylisoleucylglutaminylasparaginylalanylthreonylleucylarginylalanylphenylalanylalanylalanylglycylvalylthreonylprolylalanylglutaminylcysteinylphenylalanylglutamylmethionylleucylalanylleucylisoleucylarginylglutaminyllysylhistidylprolylthreonylisoleucylprolylisoleucylglycylleucylleucylmethionyltyrosylalanylasparaginylleucylvalylphenylalanylasparaginyllysylglycylisoleucylaspartylglutamylphenylalanyltyrosylalanylglutaminylcysteinylglutamyllysylvalylglycylvalylaspartylserylvalylleucylvalylalanylaspartylvalylprolylvalylglutaminylglutamylserylalanylprolylphenylalanylarginylglutaminylalanylalanylleucylarginylhistidylasparaginylvalylalanylprolylisoleucylphenylalanylisoleucylcysteinylprolylprolylaspartylalanylaspartylaspartylaspartylleucylleucylarginylglutaminylisoleucylalanylseryltyrosylglycylarginylglycyltyrosylthreonyltyrosylleucylleucylserylarginylalanylglycylvalylthreonylglycylalanylglutamylasparaginylarginylalanylalanylleucylprolylleucylasparaginylhistidylleucylvalylalanyllysylleucyllysylglutamyltyrosylasparaginylalanylalanylprolylprolylleucylglutaminylglycylphenylalanylglycylisoleucylserylalanylprolylaspartylglutaminylvalyllysylalanylalanylisoleucylaspartylalanylglycylalanylalanylglycylalanylisoleucylserylglycylserylalanylisoleucylvalyllysylisoleucylisoleucylglutamylglutaminylhistidylasparaginylisoleucylglutamylprolylglutamyllysylmethionylleucylalanylalanylleucyllysylvalylphenylalanylvalylglutaminylprolylmethionyllysylalanylalanylthreonylarginylserine",
    "seryltyrosylserylisoleucylthreonylserylprolylserylglutaminylphenylalanylvalylphenylalanylleucylserylserylvalyltryptophylalanylaspartylprolylysoleucylglutamylleucylleucylasparaginylvalylcysteinylthreonylserylserylleucylglycylasparaginylglutaminylphenylalanylglutaminylthreonylglutaminylglutaminylalanylarginylthreonylthreonylglutaminylvalylglutaminylglutaminylphenylalanylserylglutaminylvalyltryptophyllysylprolylphenylalanylprolylglutaminylserylthreonylvalylarginylphenylalanylprolylglycylaspartylvalyltyrosyllysylvalyltyrosylarginyltyrosylasparaginylalanylvalylleucylaspartylprolylleucylisoleucylthreonylalanylleucylleucylglycylthreonylphenylalanylaspartylthreonylarginylasparaginylarginylisoleucylisoleucylglutamylvalylglutamylasparaginylglutaminylglutaminylserylprolylthreonylthreonylalanylglutamylthreonylleucylaspartylalanylthreonylarginylarginylvalylaspartylaspartylalanylthreonylvalylalanylisoleucylarginylserylalanylasparaginylisoleucylasparaginylleucylvalylasparaginylglutamylleucylvalylarginylglycylthreonylglycylleucyltyrosylasparaginylglutaminylasparaginylthreonylphenylalanylglutamylserylmethionylserylglycylleucylvalyltryptophylthreonylserylalanylprolylalanylserylserylserylserylserylserylseryl",
    "abcdefghijklmnopqrstuvwxyzabcdefghijklmnopqrstuvwxyzabcdefghijklmnopqrstuvwxyzabcdefghijklmnopqrstuvwxyzabcdefghijklmnopqrstuvwxyzabcdefghijklmnopqrstuvwxyzabcdefghijklmnopqrstuvwxyzabcdefghijklmnopqrstuvwxyz",
    "pneumonoultramicroscopicsilicovolcanoconiosispneumonoultramicroscopicsilicovolcanoconiosispneumonoultramicroscopicsilicovolcanoconiosis",
    "supercalifragilisticexpialidocioussupercalifragilisticexpialidocioussupercalifragilisticexpialidocioussupercalifragilisticexpialidocious",
    "titinchemicalnamefullstartmethionylthreonylthreonylglutaminylarginyltyrosylglutamylserylleucylphenylalanylalanylglutaminylleucyllysylglutamylarginyllysylglutamylglycylalanylphenylalanylvalylprolylphenylalanylvalylthreonylleucylglycylaspartylprolylglycylisoleucylglutamylglutaminylserylleucyllysylisoleucylaspartylthreonylleucylisoleucylglutamylalanylglycylalanylaspartylalanylleucylglutamylleucylglycylisoleucylprolylphenylalanylserylaspartylprolylleucylalanylaspartylglycylprolylthreonylisoleucylglutaminylasparaginylalanylthreonylleucylarginylalanylphenylalanylalanylalanylglycylvalylthreonylprolylalanylglutaminylcysteinylphenylalanylglutamylmethionylleucylalanylleucylisoleucylarginylglutaminyllysylhistidylprolylthreonylisoleucylprolylisoleucylglycylleucylleucylmethionyltyrosylalanylasparaginylleucylvalylphenylalanylasparaginyllysylglycylisoleucylaspartylglutamylphenylalanyltyrosylalanylglutaminylcysteinylglutamyllysylvalylglycylvalylaspartylserylvalylleucylvalylalanylaspartylvalylprolylvalylglutaminylglutamylserylalanylprolylphenylalanylarginylglutaminylalanylalanylleucylarginylhistidylasparaginylvalylalanylprolylisoleucylphenylalanylisoleucylcysteinylprolylprolylaspartylalanylaspartylaspartylaspartylleucylleucylarginylglutaminylisoleucylalanylseryltyrosylglycylarginylglycyltyrosylthreonyltyrosylleucylleucylserylarginylalanylglycylvalylthreonylglycylalanylglutamylasparaginylarginylalanylalanylleucylprolylleucylasparaginylhistidylleucylvalylalanyllysylleucyllysylglutamyltyrosylasparaginylalanylalanylprolylprolylleucylglutaminylglycylphenylalanylglycylisoleucylserylalanylprolylaspartylglutaminylvalyllysylalanylalanylisoleucylaspartylalanylglycylalanylalanylglycylalanylisoleucylserylglycylserylalanylisoleucylvalyllysylisoleucylisoleucylglutamylglutaminylhistidylasparaginylisoleucylglutamylprolylglutamyllysylmethionylleucylalanylalanylleucyllysylvalylphenylalanylvalylglutaminylprolylmethionyllysylalanylalanylthreonylarginylserine",
    "qwertyuiopasdfghjklzxcvbnmqwertyuiopasdfghjklzxcvbnmqwertyuiopasdfghjklzxcvbnmqwertyuiopasdfghjklzxcvbnmqwertyuiopasdfghjklzxcvbnmqwertyuiopasdfghjklzxcvbnmqwertyuiopasdfghjklzxcvbnmqwertyuiopasdfghjklzxcvbnm",
    "Nirantarandhakaritadigantarakandaladamandasudharasabindusandrataraghanaghanavrndasandehakarasyandamanamakarandabindubandhurataramakandatarukulatalpakalpamrdulasikatajalajatilamulatalamaruvakamiladalaghulaghulayakalitaramaniyapaniyasalikabalikakararavindagalantikagaladelalavangapatalaghanasarakasturikatisaurabhameduralaghutaramadhurasitalatarasaliladharanirakarisnutadiyavimalavilocanamayukharekhapasaritapipasayasapathikalokan",
    "Nonagintaoctoginseptuaginsexaginquinquaginquadragintriginvigindecillinonagintaoctoginseptuaginsexaginquinquaginquadragintriginvigindecillinonagintaoctoginseptuaginsexaginquinquaginquadragintriginvigindecillinillion",
    "Krungthepmahanakhonamonrattanakosinmahintharayuthayamahadilokphophnoppharatratchathaniburiromudomratchaniwetmahasathanamonpimanawatansathitsakkathattiyawitsanukamprasit",
    "Tweedehandsemotorverkoopsmannevakbondstakingsvergaderingsameroeperstoespraakskrywerspersverklaringuitreikingsmediakonferensieaankondiging",
    "Nalunaarasuartaateeraaranngualioiligeullioqiliffissualioriataallaqqissupilorujussuanngortartuinnakasinngortinniamisaalinnguatsiaraluallaqqooqigaminngamiaasiinngooq",
    // +5 additional impossible entries
    "pseudopseudohypoparathyroidism",
    "floccinaucinihilipilification",
    "antidisestablishmentarianism",
    "ultramicroscopicsilicovolcanoconiosis",
    "titin"
];

export const getRandomWord = (mode = 'Normal') => {
    if (mode === 'Easy') return easyWords[Math.floor(Math.random() * easyWords.length)];
    if (mode === 'Wet') return 'wet';
    if (mode === 'Normal') return normalWords[Math.floor(Math.random() * normalWords.length)];
    if (mode === 'Hard') return hardWords[Math.floor(Math.random() * hardWords.length)];
    if (mode === 'Super Hard') return superHardWords[Math.floor(Math.random() * superHardWords.length)];
    if (mode === 'Insane') return insaneWords[Math.floor(Math.random() * insaneWords.length)];
    if (mode === 'Crazy') return crazyWords[Math.floor(Math.random() * crazyWords.length)];
    if (mode === 'Master') return longWords[Math.floor(Math.random() * longWords.length)];
    if (mode === 'Impossible') return impossibleWords[Math.floor(Math.random() * impossibleWords.length)];
    return normalWords[Math.floor(Math.random() * normalWords.length)];
};
